// Generated by CoffeeScript 1.8.0
(function () {
    var __hasProp = {}.hasOwnProperty,
        __extends = function (child, parent) {
            for (var key in parent) {
                if (__hasProp.call(parent, key)) child[key] = parent[key];
            }
            function ctor() {
                this.constructor = child;
            }

            ctor.prototype = parent.prototype;
            child.prototype = new ctor();
            child.__super__ = parent.prototype;
            return child;
        };

    window.CubeDancer = (function (_super) {
        __extends(CubeDancer, _super);

        CubeDancer.name = "CubeDancer";

        function CubeDancer(dance, danceMaterial, options) {
            var position, scale, _ref;
            this.options = options;
            if (this.options != null) {
                _ref = this.options, position = _ref.position, scale = _ref.scale;
            }
            CubeDancer.__super__.constructor.call(this, new THREE.BoxGeometry(1, 1, 1), dance, danceMaterial, position, scale);
        }

        return CubeDancer;

    })(Dancer);

}).call(this);
