// Generated by CoffeeScript 1.8.0
(function() {
  window.Dancer = (function() {
    Dancer.type = Dancer;

    Dancer.params = [
      {
        name: 'position',
        "default": [0, 0, 0]
      }, {
        name: 'scale',
        "default": [0, 0, 0]
      }
    ];

    function Dancer(geometry, dance, danceMaterial, position, scale) {
      var material;
      material = danceMaterial.material;
      this.dance = dance;
      this.danceMaterial = danceMaterial;
      this.body = new THREE.Mesh(geometry, material);
      if ((position != null) && position.length === 3) {
        this.body.position.set(position[0], position[1], position[2]);
      }
      if ((scale != null) && scale.length === 3) {
        this.body.scale.set(scale[0], scale[1], scale[2]);
      }
    }

    Dancer.prototype.geometry = function() {
      return new THREE.PlaneGeometry(1, 1);
    };

    Dancer.prototype.reset = function() {
      return this.dance.reset(this);
    };

    Dancer.prototype.update = function(audioWindow) {
      this.dance.update(audioWindow, this);
      return this.danceMaterial.update(audioWindow, this);
    };

    return Dancer;

  })();

}).call(this);
