// Generated by CoffeeScript 1.8.0
(function() {
  window.Dancer = (function() {
    Dancer.type = Dancer;

    Dancer.params = [
      {
        name: 'position',
        "default": [0, 0, 0]
      }, {
        name: 'scale',
        "default": [0, 0, 0]
      }
    ];

    function Dancer(geometry, dance, danceMaterial, position, scale) {
      var material;
      material = danceMaterial.material;
      this.dance = dance;
      this.danceMaterial = danceMaterial;
      this.body = new THREE.Mesh(geometry, material);
      this.body.position = position != null ? position : new THREE.Vector3(0, 0, 0);
      this.body.scale = scale != null ? scale : new THREE.Vector3(1, 1, 1);
    }

    Dancer.prototype.geometry = function() {
      return new THREE.PlaneGeometry(1, 1);
    };

    Dancer.prototype.reset = function() {
      return this.dance.reset(this);
    };

    Dancer.prototype.update = function(audioWindow) {
      this.dance.update(audioWindow, this);
      return this.danceMaterial.update(audioWindow, this);
    };

    return Dancer;

  })();

}).call(this);
