// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.SphereDancer = (function(_super) {
    __extends(SphereDancer, _super);

    function SphereDancer() {
      return SphereDancer.__super__.constructor.apply(this, arguments);
    }

    SphereDancer.constructor = function() {
      return SphereDancer.__super__.constructor.constructor.call(this, new THREE.SphereGeometry(1, 32, 24), dance, danceMaterial, position, scale);
    };

    return SphereDancer;

  })(Dancer);

}).call(this);
