// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  require('./Dancer.coffee');

  window.SphereDancer = (function(_super) {
    __extends(SphereDancer, _super);

    SphereDancer.name = "SphereDancer";

    function SphereDancer(dance, danceMaterial, options) {
      var position, scale, _ref;
      this.options = options;
      if (this.options != null) {
        _ref = this.options, position = _ref.position, scale = _ref.scale;
      }
      SphereDancer.__super__.constructor.call(this, new THREE.SphereGeometry(1, 32, 24), dance, danceMaterial, position, scale);
    }

    return SphereDancer;

  })(Dancer);

}).call(this);

//# sourceMappingURL=SphereDancer.js.map
