// Generated by CoffeeScript 1.8.0
(function() {
  window.AudioWindow = (function() {
    function AudioWindow(bufferSize, volume) {
      this.volume = volume;
      this.bufferSize = bufferSize;
      this.frequencyBuffer = new Uint8Array(bufferSize);
      this.dbBuffer = new Uint8Array(bufferSize);
    }

    AudioWindow.prototype.update = function(analyser) {
      var buf, rms, val, _i, _len, _ref;
      if (!analyser) {
        return;
      }
      analyser.getByteTimeDomainData(this.dbBuffer);
      analyser.getByteFrequencyData(this.frequencyBuffer);
      rms = 0;
      _ref = this.dbBuffer;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        buf = _ref[_i];
        val = (buf - 128) / 128;
        rms += val * val;
      }
      return this.averageDb = Math.sqrt(rms / this.bufferSize) * this.volume;
    };

    return AudioWindow;

  })();

}).call(this);
