// Generated by CoffeeScript 1.8.0
(function() {
  window.AudioWindow = (function() {
    function AudioWindow(bufferSize, responsiveness) {
      this.responsiveness = responsiveness;
      this.bufferSize = bufferSize;
      this.frequencyBuffer = new Uint8Array(bufferSize);
      this.dbBuffer = new Uint8Array(bufferSize);
      this.time = 0;
      this.deltaTime = 0;
    }

    AudioWindow.prototype.update = function(analyser, time) {
      var buf, newTime, rms, val, _i, _len, _ref;
      if (!analyser) {
        return;
      }
      newTime = time * 1000;
      this.deltaTime = newTime - this.time;
      this.time = newTime;
      analyser.getByteTimeDomainData(this.dbBuffer);
      analyser.getByteFrequencyData(this.frequencyBuffer);
      rms = 0;
      _ref = this.dbBuffer;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        buf = _ref[_i];
        val = (buf - 128) / 128;
        rms += val * val;
      }
      return this.averageDb = Math.sqrt(rms / this.bufferSize) * this.responsiveness;
    };

    return AudioWindow;

  })();

}).call(this);

//# sourceMappingURL=AudioWindow.js.map
