// Generated by CoffeeScript 1.8.0
(function() {
  window.Dance = (function() {
    function Dance() {}

    Dance.prototype.update = function(audioWindow, dancer) {
      var averageDb;
      averageDb = audioWindow.averageDb;
      return dancer.body.scale.set(averageDb, averageDb, averageDb);
    };

    return Dance;

  })();

}).call(this);
