// Generated by CoffeeScript 1.8.0
(function() {
  window.Dancer = (function() {
    function Dancer() {
      var geometry, material;
      geometry = new THREE.BoxGeometry(1, 1, 1);
      material = new THREE.MeshBasicMaterial({
        color: 0xff0000
      });
      this.body = new THREE.Mesh(geometry, material);
      this.body.position = new THREE.Vector3(0, 0, 0);
      this.dance = new ScaleDance(0.7);
      this.danceMaterial = new ColorDanceMaterial(0.01);
    }

    Dancer.prototype.update = function(audioWindow) {
      this.dance.update(audioWindow, this);
      return this.danceMaterial.update(audioWindow, this);
    };

    return Dancer;

  })();

}).call(this);
