// Generated by CoffeeScript 1.8.0
(function() {
  window.Event = (function() {
    function Event(samples) {
      this.frequencySamples = new Uint8Array(samples);
      this.dbSamples = new Uint8Array(samples);
    }

    return Event;

  })();

}).call(this);
