// Generated by CoffeeScript 1.8.0
(function() {
  window.DatGUIInterface = (function() {
    function DatGUIInterface() {}

    return DatGUIInterface;

  })();

}).call(this);

//# sourceMappingURL=GUIInterface.js.map
