// Generated by CoffeeScript 1.8.0
(function() {
  window.MainViewer = (function() {
    function MainViewer() {
      this.visualizerViewer = new VisualizerViewer();
      this.visualizerViewer.addEventListener();
    }

    return MainViewer;

  })();

  $(function() {
    window.app = new MainViewer();
    return dat.GUI.prototype.removeFolder = function(name) {
      var folder;
      folder = this.__folders[name];
      if (!folder) {
        return;
      }
      folder.close();
      this.__ul.removeChild(folder.domElement.parentNode);
      delete this.__folders[name];
      return this.onResize();
    };
  });

}).call(this);
