// Generated by CoffeeScript 1.8.0
(function() {
  var Player;

  Player = (function() {
    function Player() {}

    Player.prototype.createLiveInput = function(next) {};

    Player.prototype.stream = function(url, next) {};

    return Player;

  })();

}).call(this);
