// Generated by CoffeeScript 1.8.0
(function() {
  window.VisualizerViewer = (function() {
    function VisualizerViewer() {
      this.domain = window.location.protocol + '//' + window.location.host;
    }

    VisualizerViewer.prototype.addEventListener = function() {
      return window.addEventListener('message', (function(_this) {
        return function(event) {
          if (event.origin !== _this.domain) {
            return;
          }
          return _this.receiveEvent(event);
        };
      })(this));
    };

    VisualizerViewer.prototype.receiveEvent = function(event) {
      return console.log(event);
    };

    return VisualizerViewer;

  })();

}).call(this);
