// Generated by CoffeeScript 1.8.0
(function() {
  window.PositionDance = (function() {
    function PositionDance(smoothingFactor) {
      this.smoothingFactor = smoothingFactor;
      this.positionChange = 0;
      this.direction = new THREE.Vector3(0, 1, 0);
    }

    PositionDance.prototype.update = function(audioWindow, dancer, direction) {
      var basePosition, newPosition;
      if (direction == null) {
        direction = this.direction;
      }
      basePosition = dancer.body.position - this.direction.multiplyScalar(this.positionChange);
      this.direction = direction;
      this.positionChange = audioWindow.averageDb * this.smoothingFactor + (1 - this.smoothingFactor) * this.positionChange;
      newPosition = new THREE.Vector3();
      newPosition.addVectors(basePosition, this.direction.multiplyScalar(this.positionChange));
      return dancer.body.position.set(newPosition.x, newPosition.y, newPosition.z);
    };

    return PositionDance;

  })();

}).call(this);
