// Generated by CoffeeScript 1.8.0
(function () {
    window.RotateDance = (function () {
        RotateDance.name = "RotateDance";

        RotateDance.params = [
            {
                name: 'axis',
                "default": [0, 1, 0]
            },
            {
                name: 'minRotation',
                "default": 0.05
            },
            {
                name: 'speed',
                "default": 1
            }
        ];

        function RotateDance(options) {
            var axis, _ref;
            this.options = options;
            if (this.options != null) {
                _ref = this.options, axis = _ref.axis, this.minRotation = _ref.minRotation, this.speed = _ref.speed;
            }
            if (this.minRotation == null) {
                this.minRotation = 0.05;
            }
            if (this.speed == null) {
                this.speed = 1;
            }
            if (axis == null) {
                axis = [0, 1, 0];
            }
            this.axis = new THREE.Vector3(axis[0], axis[1], axis[2]);
            this.time = 0;
        }

        RotateDance.prototype.update = function (audioWindow, dancer) {
            var absRotation;
            absRotation = audioWindow.averageDb * this.speed;
            dancer.body.rotateOnAxis(this.axis, (this.minRotation + absRotation * 0.9) * Math.PI * ((audioWindow.time - this.time) / 1000));
            return this.time = audioWindow.time;
        };

        RotateDance.prototype.reset = function (dancer) {
            return dancer.body.rotation.set(0, 0, 0);
        };

        return RotateDance;

    })();

}).call(this);
