// Generated by CoffeeScript 1.8.0
(function() {
  window.ScaleDance = (function() {
    function ScaleDance(options) {
      this.smoothingFactor = options.smoothingFactor;
      this.averageDb = 0;
    }

    ScaleDance.prototype.update = function(audioWindow, dancer) {
      var smoothingFactor;
      if (audioWindow.averageDb < this.averageDb) {
        this.averageDb = audioWindow.averageDb * this.smoothingFactor + (1 - this.smoothingFactor) * this.averageDb;
      } else {
        smoothingFactor = Math.max(1, this.smoothingFactor * 4);
        this.averageDb = audioWindow.averageDb * smoothingFactor + (1 - smoothingFactor) * this.averageDb;
      }
      return dancer.body.scale.set(this.averageDb, this.averageDb, this.averageDb);
    };

    ScaleDance.prototype.reset = function(dancer) {
      return dancer.body.scale.set(1, 1, 1);
    };

    return ScaleDance;

  })();

}).call(this);
