// Generated by CoffeeScript 1.8.0
(function() {
  window.ColorDanceMaterial = (function() {
    function ColorDanceMaterial(smoothingFactor) {
      this.smoothingFactor = smoothingFactor;
      this.newColor = 0;
      this.material = new THREE.MeshLambertMaterial({
        color: 0x00000,
        wireframe: true
      });
    }

    ColorDanceMaterial.prototype.update = function(audioWindow, dancer) {
      var freq, i, maxImportantIndex, maxIndex, maxValue, newColor, value, _i, _ref;
      maxValue = 0;
      maxIndex = -1;
      maxImportantIndex = 1;
      for (i = _i = 1, _ref = audioWindow.bufferSize; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        freq = audioWindow.frequencyBuffer[i];
        value = freq * i;
        if (value > maxValue) {
          maxValue = value;
          maxIndex = i;
        }
        if (value > maxValue / 10) {
          maxImportantIndex = i;
        }
      }
      newColor = 0xffffff * (maxIndex / maxImportantIndex);
      this.newColor = this.smoothingFactor * newColor + (1 - this.smoothingFactor) * this.newColor;
      dancer.body.material.emissive.setHex(this.newColor);
      return dancer.body.material.color.setHex(this.newColor);
    };

    return ColorDanceMaterial;

  })();

}).call(this);
