// Generated by CoffeeScript 1.8.0
(function() {
  window.Dance = (function() {
    function Dance() {}

    Dance.prototype.update = function(audioEvent) {};

    return Dance;

  })();

}).call(this);
