// Generated by CoffeeScript 1.8.0
(function() {
  window.Dancer = (function() {
    function Dancer() {}

    Dancer.prototype.rendeer = function(audioEvent) {};

    return Dancer;

  })();

}).call(this);
