// Generated by CoffeeScript 1.8.0
(function() {
  window.Dancer = (function() {
    function Dancer() {
      var geometry, material;
      geometry = new THREE.BoxGeometry(1, 1, 1);
      material = new THREE.MeshBasicMaterial({
        color: 0xff0000
      });
      this.body = new THREE.Object3D(geometry, material);
      this.body.position = new THREE.Vector3(0, 0, 0);
    }

    Dancer.prototype.update = function(audioEvent) {};

    return Dancer;

  })();

}).call(this);
