// Generated by CoffeeScript 1.8.0
(function() {
  window.Effect = (function() {
    function Effect() {}

    Effect.prototype.update = function(audioEvent) {};

    return Effect;

  })();

}).call(this);
