// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.Main = (function() {
    function Main() {
      this.onWindowResize = __bind(this.onWindowResize, this);
      var visualizer;
      this.scene = new THREE.Scene();
      this.renderer = new THREE.WebGLRenderer({
        antialias: true,
        alpha: false
      });
      this.renderer.setClearColor(0x9C9C9C);
      this.renderer.setSize(window.innerWidth, window.innerHeight);
      this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
      window.addEventListener('resize', this.onWindowResize, false);
      document.body.appendChild(this.renderer.domElement);
      visualizer = new Visualizer();
    }

    Main.prototype.render = function() {
      visualizer.render();
      this.scene.updateMatrixWorld();
      this.renderer.clear();
      this.renderer.render(this.scene, this.camera);
    };

    Main.prototype.onWindowResize = function() {
      this.camera.aspect = window.innerWidth / window.innerHeight;
      this.camera.updateProjectionMatrix();
      return this.renderer.setSize(window.innerWidth, window.innerHeight);
    };

    return Main;

  })();

  window.animate = function() {
    requestAnimationFrame(window.animate);
    return window.app.render();
  };

  $(function() {
    window.app = new Main();
    return window.animate();
  });

}).call(this);
