// Generated by CoffeeScript 1.8.0
(function() {
  window.Visualizer = (function() {
    Visualizer.prototype.keys = {
      PAUSE: 32,
      NEXT: 78
    };

    function Visualizer(viewer) {
      this.viewer = viewer;
      this.audioWindow = new AudioWindow(2048, 1);
      this.loadedAudio = new Array();
      this.startOffset = 0;
      this.setupAnalyser();
      this.createLiveInput();
      this.choreographyRoutine = new ChoreographyRoutine(this);
      this.setupGUI();
      this.choreographyRoutine.playNext();
    }

    Visualizer.prototype.setupAnalyser = function() {
      window.AudioContext = window.AudioContext || window.webkitAudioContext;
      this.audioContext = new AudioContext();
      this.analyser = this.audioContext.createAnalyser();
      return this.analyser.fftSize = 2048;
    };

    Visualizer.prototype.setupPopup = function() {
      return $('#viewerButton').click((function(_this) {
        return function(e) {
          var popupURL, sendBeats;
          e.preventDefault();
          _this.domain = window.location.protocol + '//' + window.location.host;
          popupURL = _this.domain + location.pathname + 'viewer.html';
          _this.popup = window.open(popupURL, 'myWindow');
          sendBeats = function() {
            var routineBeat, _results;
            routineBeat = _this.choreographyRoutine.routineBeat;
            _this.choreographyRoutine.routineBeat = -1;
            _results = [];
            while (_this.choreographyRoutine.routineBeat < routineBeat) {
              _results.push(_this.choreographyRoutine.playNext());
            }
            return _results;
          };
          return setTimeout(sendBeats, 100);
        };
      })(this));
    };

    Visualizer.prototype.setupGUI = function() {
      var danceController, danceFolder, danceMaterialController, danceMaterialFolder, dancerController, dancerFolder, gui, idController, setupFolder, updateFolder, _ref, _ref1, _ref2;
      gui = new dat.GUI();
      gui.add(this.audioWindow, 'responsiveness', 0.0, 5.0);
      idController = gui.add(this.choreographyRoutine, 'id');
      setupFolder = (function(_this) {
        return function(name, varName, keys) {
          var controller, folder;
          controller = gui.add(_this.choreographyRoutine, varName, keys);
          folder = gui.addFolder(name);
          folder.open();
          return {
            controller: controller,
            folder: folder
          };
        };
      })(this);
      updateFolder = function(types, folder, params, value, obj) {
        var param, _i, _len, _ref, _ref1, _results;
        if (types[value] == null) {
          return;
        }
        while (folder.__controllers[0] != null) {
          folder.remove(folder.__controllers[0]);
        }
        _ref = types[value].params;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          param = _ref[_i];
          params[param.name] = (obj != null ? (_ref1 = obj.options) != null ? _ref1[param.name] : void 0 : void 0) ? obj.options[param.name] : param["default"];
          _results.push(folder.add(params, param.name));
        }
        return _results;
      };
      _ref = setupFolder('Dancer parameters', 'dancer', Object.keys(Visualizer.dancerTypes)), dancerController = _ref.dancerController, dancerFolder = _ref.dancerFolder;
      dancerController.onChange((function(_this) {
        return function(value, obj) {
          return updateFolder(Visualizer.dancerTypes, dancerFolder, _this.choreographyRoutine.dancerParams, value, obj);
        };
      })(this));
      _ref1 = setupFolder('Dance parameters', 'dance', Object.keys(Visualizer.danceTypes)), danceController = _ref1.danceController, danceFolder = _ref1.danceFolder;
      danceController.onChange((function(_this) {
        return function(value, obj) {
          return updateFolder(Visualizer.danceTypes, danceFolder, _this.choreographyRoutine.danceParams, value, obj);
        };
      })(this));
      _ref2 = setupFolder('Dance material paramaters', 'danceMaterial', Object.keys(Visualizer.danceMaterialTypes)), danceMaterialController = _ref2.danceMaterialController, danceMaterialFolder = _ref2.danceMaterialFolder;
      danceMaterialController.onChange((function(_this) {
        return function(value, obj) {
          return updateFolder(Visualizer.danceMaterialTypes, danceMaterialFolder, _this.choreographyRoutine.danceMaterialParams, value, obj);
        };
      })(this));
      idController.onChange((function(_this) {
        return function(value) {
          var controller, idDancer, _i, _len, _ref3;
          idDancer = _this.viewer.getDancer(value);
          if (idDancer != null) {
            _this.choreographyRoutine.updateDancer(idDancer);
            _ref3 = gui.__controllers;
            for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
              controller = _ref3[_i];
              controller.updateDisplay();
            }
            updateDancerFolder(_this.choreographyRoutine.dancer, idDancer);
            updateDanceMaterialFolder(_this.choreographyRoutine.danceMaterial, idDancer.danceMaterial);
            return updateDanceFolder(_this.choreographyRoutine.dance, idDancer.dance);
          }
        };
      })(this));
      gui.add(this.choreographyRoutine, 'preview');
      gui.add(this.choreographyRoutine, 'add');
      gui.add(this.choreographyRoutine, 'insertBeat');
      gui.add(this.choreographyRoutine, 'playNext');
      return gui.add(this.choreographyRoutine, 'reset');
    };

    Visualizer.prototype.receiveChoreography = function(move) {
      this.viewer.receiveChoreography(move);
      if (this.popup != null) {
        return this.popup.postMessage(this.wrapMessage('choreography', move), this.domain);
      }
    };

    Visualizer.prototype.render = function() {
      if (!this.playing) {
        return;
      }
      this.audioWindow.update(this.analyser, this.audioContext.currentTime);
      this.viewer.render(this.audioWindow);
      if (this.popup != null) {
        return this.popup.postMessage(this.wrapMessage('render', this.audioWindow), this.domain);
      }
    };

    Visualizer.prototype.wrapMessage = function(type, data) {
      return {
        type: type,
        data: data
      };
    };

    Visualizer.prototype.onKeyDown = function(event) {
      switch (event.keyCode) {
        case this.keys.PAUSE:
          if (this.playing) {
            return this.pause();
          } else {
            return this.play(this.currentlyPlaying);
          }
          break;
        case this.keys.NEXT:
          return this.choreographyRoutine.playNext();
      }
    };

    Visualizer.dancerTypes = {
      CubeDancer: CubeDancer,
      SphereDancer: SphereDancer,
      PointCloudDancer: PointCloudDancer
    };

    Visualizer.danceTypes = {
      ScaleDance: ScaleDance,
      PositionDance: PositionDance,
      RotateDance: RotateDance
    };

    Visualizer.danceMaterialTypes = {
      ColorDanceMaterial: ColorDanceMaterial,
      SimpleFrequencyShader: SimpleFrequencyShader
    };

    Visualizer.prototype.pause = function() {
      this.source.stop();
      this.playing = false;
      return this.startOffset += this.audioContext.currentTime - this.startTime;
    };

    Visualizer.prototype.createLiveInput = function() {
      var gotStream;
      gotStream = (function(_this) {
        return function(stream) {
          _this.playing = true;
          _this.source = _this.audioContext.createMediaStreamSource(stream);
          return _this.source.connect(_this.analyser);
        };
      })(this);
      this.dbSampleBuf = new Uint8Array(2048);
      if (navigator.getUserMedia) {
        return navigator.getUserMedia({
          audio: true
        }, gotStream, function(err) {
          return console.log(err);
        });
      } else if (navigator.webkitGetUserMedia) {
        return navigator.webkitGetUserMedia({
          audio: true
        }, gotStream, function(err) {
          return console.log(err);
        });
      } else if (navigator.mozGetUserMedia) {
        return navigator.mozGetUserMedia({
          audio: true
        }, gotStream, function(err) {
          return console.log(err);
        });
      } else {
        return alert("Error: getUserMedia not supported!");
      }
    };

    Visualizer.prototype.play = function(url) {
      var request;
      this.currentlyPlaying = url;
      if (this.loadedAudio[url] != null) {
        this.loadFromBuffer(this.loadedAudio[url]);
        return;
      }
      request = new XMLHttpRequest();
      request.open("GET", url, true);
      request.responseType = 'arraybuffer';
      request.onload = (function(_this) {
        return function() {
          _this.audioContext.decodeAudioData(request.response, function(buffer) {
            _this.loadedAudio[url] = buffer;
            return _this.loadFromBuffer(buffer);
          }, function(err) {
            return console.log(err);
          });
        };
      })(this);
      request.send();
    };

    Visualizer.prototype.loadFromBuffer = function(buffer) {
      this.startTime = this.audioContext.currentTime;
      this.source = this.audioContext.createBufferSource();
      this.source.buffer = buffer;
      this.source.connect(this.analyser);
      this.source.connect(this.audioContext.destination);
      this.playing = true;
      return this.source.start(0, this.startOffset);
    };

    return Visualizer;

  })();

}).call(this);

//# sourceMappingURL=Visualizer.js.map
