// Generated by CoffeeScript 1.8.0
(function() {
  window.Visualizer = (function() {
    function Visualizer(main) {}

    Visualizer.prototype.render = function() {};

    return Visualizer;

  })();

}).call(this);
